AsianHouse MVC/AsianHouse.MVC/Controllers/ItemGroupController.cs
using System.Linq;
using System.Web.Mvc;
using AsianHouse.Domain.Model;
using AsianHouse.Domain.Repositories;

namespace AsianHouse.MVC.Controllers
{
    public class ItemGroupController : Controller
    {
        private readonly IRepository<ItemGroup> _repository;

        public ItemGroupController(IRepository<ItemGroup> repository)
        {
            this._repository = repository;
        }

        // GET: /ItemGroup/
        public ActionResult Index()
        {
            ViewBag.Message = "Liste over varegrupper";

            var itemGroupList = _repository.GetAll();

            //var session = NHibernateHelper.CreateSessionFactory().OpenSession();

            //IQueryable<ItemGroup> rep = session.Query<ItemGroup>();

            //var itemg = rep.Single(ig => ig.Id == 2);


            //var iSession = NHibernateHelper.CreateSessionFactory();
            //var repo = new Repository<ItemGroup>(iSession.OpenSession());
            //var result = repo.FindById(1);

            return View("Index", itemGroupList.ToList());
        }

        //
        // GET: /ItemGroup/Details/5
        public ActionResult Details(int id)
        {

            var itemGroup = _repository.FindById(id);

            ViewBag.Title = itemGroup.Name;

            return View(itemGroup);

        }

        //
        // GET: /ItemGroup/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /ItemGroup/Create

        [HttpPost, Authorize(Roles = "admin")]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /ItemGroup/Edit/5

        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /ItemGroup/Edit/5

        [HttpPost, Authorize(Roles = "admin")]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /ItemGroup/Delete/5

        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /ItemGroup/Delete/5

        [HttpPost, Authorize(Roles = "admin")]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}
    

AsianHouse MVC/AsianHouse.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
    <head>
        <title>Asian House &#174; . @ViewBag.Title</title>
        @*<link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />*@
        <link href="@Url.Content("~/Content/style.css")" type="text/css" rel="stylesheet" />
        <script src="@Url.Content("~/Scripts/jquery-1.4.4.min.js")" type="text/javascript"></script>
        <script src="@Url.Content("~/Scripts/AH/allscripts.js")" type="text/javascript"></script>
    </head>
    <body onload="PreLoadImages();">

   @* <div class="page">

        <div id="header">
            <div id="menucontainer">

                <ul id="menu">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Varegrupper", "Index", "ItemGroup")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                </ul>
            </div>
        </div>
    </div>*@

		<div class="centertable">
			<table width="760">
				<tr class="black">
					<td style="Width:100px;"></td><td style="Width:660px;" class="center" ><img src="@Url.Content("~/Content/billeder/AHlogo.jpg")" alt="Asian House logo"/></td>
				</tr>
				<tr>
					<td class="black" id="NavPlaceHolder" style="vertical-align:top;">
					    <br/>
                        <table>
	                        <tr>
		                        <td><a onmouseover="document.getElementById('velkommen').src='/Content/billeder/velkommen_gold.gif';"
				                        onmouseout="document.getElementById('velkommen').src='/Content/billeder/velkommen_red.gif';"
				                        href="@Url.Content("/")"><img src="@Url.Content("~/Content/billeder/velkommen_red.gif")" 
                                        alt="Tilbage til hovedsiden" 
                                        id="velkommen"/></a></td>
	                        </tr>
	                        <tr>
		                        <td><a onmouseover="document.getElementById('info').src='/Content/billeder/info_gold.gif';" 
                                        onmouseout="document.getElementById('info').src='/Content/billeder/info_red.gif';"
				                        href="/information"><img alt="Information" src="@Url.Content("~/Content/billeder/info_red.gif")" 
                                        id="info"/></a></td>
	                        </tr>
	                        <tr>
		                        <td><a onmouseover="document.getElementById('produkter').src='/Content/billeder/produkter_gold.gif';"
				                        onmouseout="document.getElementById('produkter').src='/Content/billeder/produkter_red.gif';"
				                        href="/produkter/"><img alt="Produkter" src="@Url.Content("~/Content/billeder/produkter_red.gif")" 
                                        id="produkter"/></a></td>
	                        </tr>
	                        <tr>
		                        <td><a onmouseover="document.getElementById('privat').src='/Content/billeder/privat_gold.gif';"
				                        onmouseout="document.getElementById('privat').src='/Content/billeder/privat_red.gif';"
				                        href="/privat"><img alt="Private" src="@Url.Content("~/Content/billeder/privat_red.gif")" 
                                        id="privat"/></a></td>
	                        </tr>
	                        <tr>
		                        <td><a onmouseover="document.getElementById('forhandler').src='/Content/billeder/forhandler_gold.gif';"
				                        onmouseout="document.getElementById('forhandler').src='/Content/billeder/forhandler_red.gif';"
				                        href="/erhverv"><img alt="Forhandlere" src="@Url.Content("~/Content/billeder/forhandler_red.gif")" 
                                        id="forhandler"/></a></td>
	                        </tr>
	                        <tr>
		                        <td><a onmouseover="document.getElementById('messer').src='/Content/billeder/messer_gold.gif';"
				                        onmouseout="document.getElementById('messer').src='/Content/billeder/messer_red.gif';"
				                        href="/messer"><img alt="Messer" src="@Url.Content("~/Content/billeder/messer_red.gif")" 
                                        id="messer"/></a></td>
	                        </tr>
	                        <tr>
		                        <td><a onmouseover="document.getElementById('showroom').src='/Content/billeder/showroom_gold.gif';"
				                        onmouseout="document.getElementById('showroom').src='/Content/billeder/showroom_red.gif';"
				                        href="/showroom">
                                        <img alt="Showroom" src="@Url.Content("~/Content/billeder/showroom_red.gif")" id="showroom"/>
                                    </a>
                                </td>
	                        </tr>
	                        <tr>
		                        <td>&nbsp;</td>
	                        </tr>
	                        <tr>
		                        <td><a onmouseover="document.getElementById('email').src='/Content/billeder/email_gold.gif';" 
                                        onmouseout="document.getElementById('email').src='/Content/billeder/email_red.gif';"
				                        href="&#x6D;&#x61;&#x69;&#x6C;&#x74;&#x6F;&#x3A;&#x6F;&#x66;&#x66;&#x69;&#x63;&#x65;&#x40;&#x61;&#x73;&#x69;&#x61;&#x6E;&#x68;&#x6F;&#x75;&#x73;&#x65;&#x2E;&#x64;&#x6B;">
                                        <img alt="Email" src="@Url.Content("~/Content/billeder/email_red.gif")" id="email"/>
                                     </a>
                                </td>
	                        </tr>
                        </table>
					</td>
					<td class="centerpage" style="Width:600px;vertical-align:top;">
                        <div id="logindisplay" style="text-align:right;">
                            @Html.Partial("_LogOnPartial")
                        </div>
					<div id="main">
                        @RenderBody()
                        <div id="footer" class="center">Est.1992 &copy; All Rights Reserved</div>
                    </div>
                    </td>
				</tr>
			</table>
		</div>
		<script src="http://www.google-analytics.com/urchin.js" type="text/javascript" />

        <script type="text/javascript">
            _uacct = "UA-797684-8";
            urchinTracker();
        </script>

    </body>
</html>

AsianHouse MVC/AsianHouse.MVC/Views/Shared/_LogOnPartial.cshtml
@if(Request.IsAuthenticated) 
{
    <text>Logget ind som <b>@Context.User.Identity.Name</b>!

    @if(Context.User.IsInRole("admin")) 
    {
        <text>[ @Html.ActionLink("Admin", "LogOff", "Account") ]</text>
    }

    [ @Html.ActionLink("Log af", "LogOff", "Account") ]</text>
}
else {
    @:[ @Html.ActionLink("Log ind", "LogOn", "Account") ]
}